### PR TITLE
Check if ASSETS_DIR actually exists before copying

### LINKED ISSUE #7: Non-existent assets directory causes failure
**Describe the bug**
Pretty much as described. While perhaps not a best practice, there are plugins out there without screenshots or branding imagery.

**Steps to Reproduce**
1. Tag a release on a repo without a `.wordpress-org` directory.
2. Check Action run.
3. See error

```
rsync: change_dir "/github/workspace/.wordpress-org" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
##[error]Docker run failed with exit code 23
```

**Expected behavior**
It should check for the directory and skip if doesn’t exist.

**Additional context**
This is a companion issue to describe the problem #6 is solving. A parallel one will need to be opened for the asset updater action.

### PR DESCRIPTION
**Pull request by vincenzo**
### Description of the Change

Added a check to verify that `ASSETS_DIR` actually exists before attempting to copy assets over. Fixes #7  

### Benefits

This would avoid the following error when no ASSETS_DIR is present: 

```
rsync: change_dir "/github/workspace/.wordpress-org" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
##[error]Docker run failed with exit code 23
```

### Possible Drawbacks

None I can think of.

### Verification Process

Tested the affected portion of the script locally. 

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by helen** [comment]
@vincenzo Thanks for this. If you’re able to spend a little more time on this PR, I’d like to add an info message if there’s no assets dir to copy, just in case it’s an issue of not having specified your assets directory in the workflow file. If not, just let me know and I’ll handle that before merging.

Fixes #7

**Comment by nielslange** [comment]
@helen Could you add the info message as proposed in https://github.com/10up/action-wordpress-plugin-deploy/pull/6#issuecomment-528866675 and merge this PR to fix this issue?

File: entrypoint.sh [hunk 1]
```diff
@@ -92,7 +92,9 @@ else
 fi
 
 # Copy dotorg assets to /assets
-rsync -rc "$GITHUB_WORKSPACE/$ASSETS_DIR/" assets/ --delete
+if [[ -d "$GITHUB_WORKSPACE/$ASSETS_DIR/" ]]; then
+	rsync -rc "$GITHUB_WORKSPACE/$ASSETS_DIR/" assets/ --delete
+fi
```
Comment (helen) [inline entrypoint.sh]:
```suggestion
else
	echo "ℹ︎ No assets directory found; skipping asset copy"
fi
```

**Comment by vincenzo** [comment]
Sorry guys. Not sure why I didn’t get notified of the previous comments, only now that it was merged!

**Comment by nielslange** [comment]
@helen Thanks for merging @vincenzo's PR. 

@helen or @vincenzo Would one of you mind taking a look at why I still receive the following error message:

```
A    /github/svn-smntcs-private-site/trunk
Checked out revision 2173365.
Updating 'assets':
A    assets/banner-1544x500.jpg
A    assets/banner-772x250.jpg
A    assets/icon-128x128.jpg
A    assets/icon-256x256.jpg
A    assets/screenshot-01.png
Updated to revision 2173365.
Updating 'trunk':
A    trunk/languages
A    trunk/template
A    trunk/languages/smntcs-private-site.pot
A    trunk/template/private-site.php
A    trunk/LICENSE.txt
A    trunk/README.md
A    trunk/README.txt
A    trunk/smntcs-smntcs-private-site.php
Updated to revision 2173365.
➤ Copying files...
ℹ︎ Using .gitattributes
[detached HEAD 0753a89] Add .gitattributes file
 1 file changed, 4 insertions(+)
 create mode 100644 .gitattributes
rsync: change_dir "/github/workspace/.wordpress-org" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
##[error]Docker run failed with exit code 23
```

This is how my [plugin structure](https://github.com/nielslange/smntcs-private-site) looks like:

```
/assets
/branches
/tags
/trunk
```

Despite the fact that I do have an assets folder that contains images, the script fails with `No such file or directory (2)` which I cannot explain currently.
